<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Backend.Api</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Backend.Application\Backend.Application.csproj" />
    <ProjectReference Include="..\Backend.Infrastructure\Backend.Infrastructure.csproj" />
    <ProjectReference Include="..\Backend.Contracts\Backend.Contracts.csproj" />
  </ItemGroup>
</Project>